### ISSUE TITLE
Instruction mis-match

### ISSUE THREAD

**Issue by brohan** [noodlemctwoodle/pf-azure-sentinel#11]
With my limited knowledge and experience with Elasticsearch for SIEM usage, I am looking forward to getting this set up to send the logs to Sentinel. Thank you for putting this together.  Going through the steps in:

https://github.com/noodlemctwoodle/pf-azure-sentinel/tree/main/Logstash-Configuration

There are some mismatches in the steps vs the actual file name for example Step 10:

Update firewall interfaces

Amend the 05-firewall.conf file

sudo nano /etc/logstash/conf.d/40-interfaces.conf
(there is no 40-interfaces.conf file recommended to download, it is now 20-interfaces.conf?)

**Comment by noodlemctwoodle** [comment]
Hello, apologies..  I've been testing some new config which I'll push on the weekend, I thought my guide was still correct.

You are correct though the interfaces file has now changed, I'll update the guide, tomorrow 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Brian Rohan ***@***.***>
Sent: Thursday, April 8, 2021 10:43:15 PM
To: noodlemctwoodle/pf-azure-sentinel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [noodlemctwoodle/pf-azure-sentinel] Instruction mis-match (#11)


With my limited knowledge and experience with Elasticsearch for SIEM usage, I am looking forward to getting this set up to send the logs to Sentinel. Thank you for putting this together. Going through the steps in:

https://github.com/noodlemctwoodle/pf-azure-sentinel/tree/main/Logstash-Configuration

There are some mismatches in the steps vs the actual file name for example Step 10:

Update firewall interfaces

Amend the 05-firewall.conf file

sudo nano /etc/logstash/conf.d/40-interfaces.conf
(there is no 40-interfaces.conf file recommended to download, it is now 20-interfaces.conf?)

**Comment by noodlemctwoodle** [comment]
@brohan be aware of cost when you bring in Firewall logs to Sentinel, they can quickly stack up if you don't keen them under monitoring 🤣

**Comment by brohan** [comment]
I can understand that for sure.

We have a new Sentinel tenant up. I followed your tutorial, I can see logs arriving on my logstash host (sudo tcpdump -A -ni any port 5141 -vv), and logstash is enabled and started (systemctl status logstash.service returns the green active (running), output config 50 has been updated with my ID and Key, and the command was run to install the logstash connector (unknown how to test if this is installed / running properly.

I have waited quite some time, and running a query in Sentinel of just pfsense_logstash_CL  returns an error.  Going into the Advanced settings in the log analytics workspace does not show any sources, and the main page show nothing being ingested.

Any thoughts on how to troubleshoot why I am not getting logs in Sentinel?

Thank you.

**Comment by noodlemctwoodle** [comment]
Do you get any errors in 

`cat /var/log/logstash/logstash-plain.log`

**Comment by brohan** [comment]
I do get errors in that log:

`[2021-04-13T08:52:58,325][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2021-04-13T08:52:58,342][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.12.0", "jruby.version"=>"jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 11.0.10+9 on 11.0.10+9 +indy +jit [linux-x86_64]"}
[2021-04-13T08:52:59,955][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-04-13T08:53:00,275][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 22, column 3 (byte 873) after ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:184:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:69:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:389:in `block in converge_state'"]}
[2021-04-13T08:53:00,410][INFO ][logstash.runner          ] Logstash shut down.
[2021-04-13T08:53:00,425][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.13.0.jar:?]
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.13.0.jar:?]
        at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:89) ~[?:?]`

**Comment by noodlemctwoodle** [comment]
Ah you have a configuration error in one of the config files and Logstash is erroring out. That's why no logs are being sent to Sentinel. 

I am away from my computer at the moment and viewing your log file on a mobile device is less than ideal. I'll jump on my PC this evening and take a look as well as update my documentation.

Apologies for the delay 😬

**Comment by noodlemctwoodle** [comment]
Fixed the documentation and added an additional step.

**Comment by noodlemctwoodle** [comment]
```
[2021-04-13T08:52:58,325][INFO ][logstash.runner ] Log4j configuration path used is: /etc/logstash/log4j2.properties 
[2021-04-13T08:52:58,342][INFO ][logstash.runner ] Starting Logstash {"logstash.version"=>"7.12.0", "jruby.version"=>"jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 11.0.10+9 on 11.0.10+9 +indy +jit [linux-x86_64]"} 
[2021-04-13T08:52:59,955][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600} 
[2021-04-13T08:53:00,275][ERROR][logstash.agent ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 22, column 3 (byte 873) after ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:184:in initialize'", "org/logstash/execution/JavaBasePipelineExt.java:69:in initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:47:in initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52:in execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:389:in block in converge_state'"]} 
[2021-04-13T08:53:00,410][INFO ][logstash.runner ] Logstash shut down. 
[2021-04-13T08:53:00,425][FATAL][org.logstash.Logstash ] Logstash stopped processing because of an error: (SystemExit) exit org.jruby.exceptions.SystemExit: (SystemExit) exit at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.13.0.jar:?] at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.13.0.jar:?] at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:89) ~[?:?]
```

**Comment by noodlemctwoodle** [comment]
@brohan  I've reposted your formatted error log above, you have a configuration error which is causing Logstash to stop processing. 

Are you able to share the configs for the following files

- 01-inputs.conf
- 20-interfaces.conf

If you don't want to post them publically, please feel free to mail them to me here  githubsupport@cleverhomes.dev. I will be removing this email from this post after 24hrs for security reasons. 

Many thanks.

**Comment by brohan** [comment]
Sent, thank you!

**Comment by noodlemctwoodle** [comment]
Perfect, I'll take a look shortly, I'll see if I can load them on my server.

**Comment by brohan** [comment]
Thank you again. Note that I am using port 5141 per the tutorial, which is the 2nd section on the inputs file, and that is what I tested with tcpdump command (per tutorial) if that make a difference.

**Comment by noodlemctwoodle** [comment]
Could be another typo problem 🤫

Please can you change to 5140, I'll change that in the docs.

**Comment by noodlemctwoodle** [comment]
- Added additional steps to guide 
- Fixed ports mismatch in the docs 5140 | 5141
- Correctly tagged all code blocks in guide
- Added additional context around naming `custom_table_name` for Microsoft plugin and restrictions
